### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by dirkschumacher**
Used `npm audit fix` to update packages with security vulnerabilities.

I ran it locally and clicked around a bit. All seems to work fine. 

```
found 33 vulnerabilities (8 low, 20 moderate, 5 high)
```

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! I'll be mostly offline this weekend, so I would rather merge this on Monday. :)

**Comment by dirkschumacher** [comment]
This is a very good idea :) #nodeploymentfriday

**Comment by dirkschumacher** [comment]
There is a nice service called [greenkeeper](https://greenkeeper.io/) that monitors the dependencies and sends PR if somethings updates. It also uses travis to automatically test the changes (if there are tests in the node package).

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by gaborcsardi** [comment]
Deployed.

**Pull request merged**
